### PR TITLE
remove python 2.6 from travis test

### PR DESCRIPTION
**Pull request by vnitinv**
Fix https://travis-ci.org/Juniper/py-junos-eznc/jobs/329367688

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Build triggered. sha1 is merged.

**Comment by jnpr-community-netdev** [comment]
Build started sha1 is merged.

**Comment by jnpr-community-netdev** [comment]
Build finished.

**Comment by hugovk** [comment]
You could also remove/update these lines:
https://github.com/Juniper/py-junos-eznc/blob/master/setup.py#L8-L9
https://github.com/Juniper/py-junos-eznc/blob/master/setup.py#L39
https://github.com/Juniper/py-junos-eznc#pip

**Comment by vnitinv** [comment]
Thanks @hugovk I will do these changes too. Or how about a pull request from you will all these changes.

**Comment by hugovk** [comment]
I think it would be best to group them in a single PR :)

**Comment by vnitinv** [comment]
@hugovk once you send your pull request, I will close mine. Your pull request can only have all the changes

**Comment by hugovk** [comment]
There we go! ==> https://github.com/Juniper/py-junos-eznc/pull/807

**Comment by vnitinv** [comment]
closing with respect to other pull request #807

**Pull request closed without merging**
