### PR TITLE
revert back 414 changes

### LINKED ISSUE #421: SW install problem after upgrade 1.2.2 release
Previously, I asked about the software installation problem in EX8208.

In release 1.2.2, I confirmed that related problems have been fixed. (github issue number #402)
But, After upgrade to 1.2.2, I got the below error.

1. Logged error message
--------------------------------
2015-08-04 13:58:35,268:x.x.x.x: Unable to install software, update_progress() takes exactly 2 arguments (3 given)

2. My software install source code (same as development guide)
------------------------------------------------------------------------------------------
```python
import os, sys, logging
from jnpr.junos import Device
from jnpr.junos.utils.sw import SW
from jnpr.junos.exception import *

host = xxx
user = xxx
passwd = xxx

package = '/home/shhwang/junos/ex8200/jinstall-ex-8200-12.3R7.7-domestic.tgz'
logfile = '/home/shhwang/var/log/junos-pyez/150804.log'
remote_path = '/var/tmp'
validate = True

def do_log (msg, level = 'info'):
    getattr (logging, level) (msg)

def update_progress (dev, report):
    # log the progress of the installing process
    do_log (report)

def main():
    # initialize logging
    logging.basicConfig (filename = logfile, level = logging.INFO,
                         format = '%(asctime)s:%(name)s: %(message)s')
    logging.getLogger().name = host
    sys.stdout.write ('Information logged in {0}\n'.format (logfile))

    # verify package exists
    if (os.path.isfile (package)):
        found = True
    else:
        msg = 'Software package does not exist: {0}. '.format (package)
        sys.exit (msg + '\nExiting program')


    #dev = Device (host = host, user = user, passwd = passwd, gather_facts = False)
    dev = Device (host = host, user = user, passwd = passwd)

    try:
        dev.open()
    except Exception as err:
        sys.stderr.write ('Cannot connect to device: {0}\n'.format (err))

    # Increase the default RPC timeout to accommodate install operations
    dev.timeout = 300

    # Create an instance of SW
    sw = SW (dev)

    try:
        do_log ('Starting the software upgrade process: {0}'.format (package))
        ok = sw.install (package = package, remote_path = remote_path,
                         progress = update_progress, validate = validate)
    except Exception as err:
        msg = 'Unable to install software, {0}'.format (err)
        do_log (msg, level = 'error')
    else:
        if ok is True:
            do_log ('Software installation complete. Rebooting')
            rsp = sw.reboot()
            do_log ('Upgrade pending reboot cycle, please be patient.')
            do_log (rsp)

    # End the NETCONF session and close the connection
    dev.close()

if __name__ == "__main__":
    main()
```

In PyEZ github: sw.py and scp.py one of history is "Move _scp_progress to SCP and enable by default" (4c4814ab15b0591d3b639b6d911370ca969160c3)

Are there any changes are associated with this error?
Please check it.

### LINKED ISSUE #422: SCP->put print progress log in loop even if progress is not defined
from jnpr.junos import Device
from jnpr.junos.utils.scp import SCP

dev = Device(host='xxxx', user='xxx', password='xxxx')
dev.open()
with SCP(dev) as scp:
    scp.put(pkg, remote_path='/var/tmp')

output:
device-xxxx: jinstall-xxx.tgz: 95256576 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95272960 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95289344 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95305728 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95322112 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95338496 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95354880 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95371264 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95387648 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95404032 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95420416 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95436800 / 952539287 (10%)

-----
-----

### PR DESCRIPTION
**Pull request by vnitinv**
resolves #421, resolves #422

### CODE REVIEW

**Comment by shermdog** [comment]
I wouldn't revert the change, just fix the issues.  This was implemented to support techpubs and make the progress funation more accessible to the users.

**Comment by vnitinv** [comment]
@shermdog Ok, let me try to fix it. Will cancel the pull request.
But to add, As discussed with others logging should be disabled by default.

**Comment by shermdog** [comment]
Others also wanted it to be on by default - we had several questions arise around logging.  IMO having a file transfer function that seemingly hangs without any status is less than user friendly.  This was a mindful decision to support the majority of users and make things as easy as possible.  If there really is blowback you can leave it in and set False by default, but at the very least by 2.0 it should be on by default.

**Comment by vnitinv** [comment]
#427 take care of this issue.

**Pull request closed without merging**
