### PR TITLE
continue upgrade if missing request system software validate

### PR DESCRIPTION
**Pull request by ckishimo**
The following error shows up when trying to upgrade a QFX5200-32C
```
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    ok = sw.install(package=pkg, validate=True, remote_path="/var/tmp", timeout=2400, progress=myprogress)
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 865, in install
    dev_timeout=timeout)
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 330, in validate
    package_name=remote_package, **kwargs).getparent()
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/home/ckishimo/.local/lib/python2.7/site-packages/jnpr/junos/device.py", line 790, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: request-package-validate, message: syntax error)
```
The call:
```
ok = sw.install(package='/home/ckishimo/jinstall-host-qfx-5e-flex-x86-64-19.2R1.8-secure-signed.tgz',
                remote_path='/var/tmp',
                progress=myprogress,
                cleanfs=True,
                force_copy=False,
                validate=True)
```
Apparently the command `request system software validate` is not available in that platform running Junos `19.2R1` or `19.1R1` or `18.4R1`, no idea why...
```
root@qfx5200> request system software ?    
Possible completions:
  add                  Add extension or upgrade package
  delete               Remove extension or upgrade package
  in-service-upgrade   In-service software upgrade
  rollback             Attempt to roll back to previous set of packages

root@qfx5200> show version               
localre:
--------------------------------------------------------------------------
Hostname: qfx5200
Model: qfx5200-32c-32q
Junos: 18.4R1.8 flex
```
Setting `validate=False` should fix the problem, however this PR ignores the error and continues with the upgrade even if `validate=True`

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
@ydnath Can you review this. I feel this should be fixed in Junos if the command is missing.

**Comment by vnitinv** [comment]
@ckishimo Request you to raise Junos bug through your support channel. This should be fixed in Junox (if applicable). We should not work around a bug in PyEZ

**Comment by ckishimo** [comment]
@vnitinv just waiting for more information but according to JTAC the validation is done by default from junos 17.3R4 onwards, so the option `validate` will not be available anymore

**Comment by vnitinv** [comment]
@ckishimo Let me check and get back to you on this

**Comment by rsmekala** [comment]
@ckishimo I approved the change, in case the RPC is not found. But, as far as I know this RPC is still valid on the latest 19.4 images.
```
root@host> request system software validate /var/tmp/py-extensions-powerpc.tgz | display xml rpc
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/19.4I0/junos">
    <rpc>
        <request-package-validate>
                <package-name>/var/tmp/py-extensions-powerpc.tgz</package-name>
        </request-package-validate>
    </rpc>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

> @vnitinv just waiting for more information but according to JTAC the validation is done by default from junos 17.3R4 onwards, so the option `validate` will not be available anymore

Can you point me to the document stating `validate` is deprecated? Will wait for your reply before I merge this request.

**Comment by ckishimo** [comment]
> Can you point me to the document stating `validate` is deprecated? Will wait for your reply before I merge this request.

@rsmekala despite I asked the same question to JTAC I only got a reference to the release notes for version 17.4 (page 22) and that the command is last seen in 17.3R3.9. I also got 2 confidential PRs which I do not have access: 

- PR 1336482 - "validate" option is missing in CLI "request system software" 
- PR 1309440 - Handle "request system software validate" on qfx TVP VC platform

Thanks

**Comment by rsmekala** [comment]
@ckishimo Looks like it not supported in QFX-tvp platforms from 17.4 according to PR AT. 

Thanks for your contribution. Will merge this after CI run. ✌️

**Comment by rsmekala** [comment]
ok to test

**Pull request merged**
