### PR TITLE
Update securityzone.yml

### PR DESCRIPTION
**Pull request by dragonballbw3**
Added // to SecurityZoneTable's item: so it works with both clustered and standalone SRX without having user create copy of this table/view for SRX clusters

### CODE REVIEW

**Comment by dragonballbw3** [comment]
The second pull request was an attempt to bring my fork up to date with upstream.  If I did that wrong, let me know.  (yes I am new to github and how to do some stuff)
Cory C.

**Comment by jacobneiltaylor** [comment]
Hey Cory,

No objections to commit, but I originally authored this particular YAML template for an internal project. I tested it against both standalone and clustered SRX deployments and can't recall having to write special handling code for each case.

I was just wondering if you could provide more detail on what usecase requires special handling from your perspective? Ideally, a snippet of your user code before and after your patch.

I'm only asking to better understand the edge case, so I can better account for it in future contributions - chances are I may run into it myself 😅. Not trying to nitpick or anything!

Cheers,
Jake

**Comment by dragonballbw3** [comment]
Hrm, maybe this has more to do with my SRXes being a High-End (SRX3K, SRX5K).  Will attach the XML output of "show security zones | display xml".

Cory C.
[get-zone-info.zip](https://github.com/Juniper/py-junos-eznc/files/2916790/get-zone-info.zip)

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by dragonballbw3** [comment]
Still waiting on this to be merged.  Issue #912 has already been closed, but I didn't see any commit related to it or reference to this PR.  Is there anything I need to do to move this forward?

**Pull request merged**
