### PR TITLE
update the symbol in ospf.yml

### PR DESCRIPTION
**Pull request by insqur**
changing the symbol from the underline to the hyphen.

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Autobot:  Would an admin like to run functional tests?

**Comment by vnitinv** [comment]
@insqur Ideally both should work. Did you face any issue with get_ospf_interface_information

**Comment by insqur** [comment]
@vnitinv No.It works well.just not using the unifined format.

**Comment by vnitinv** [comment]
@insqur reopening to merge this.

**Pull request merged**
