### PR TITLE
Created op views for dns-proxy-information & system-memory

### PR DESCRIPTION
**Pull request by pr11t**

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
@pr11t  Any specific reason why you opted for all fields as key?

**Comment by pr11t** [comment]
@vnitinv  I just figured this won't work with a chassis cluster ... Any tips on making it work without creating a separate files? Otherwise might have to scratch this patch I guess.

**Comment by pr11t** [comment]
After changing the item key I tested with both cluster and not cluster config and seems to work this way

**Pull request closed without merging**
