### PR TITLE
Handle ncclient timeout exception at close.

### PR DESCRIPTION
**Pull request by stacywsmith**
If `dev.close()` is called while another RPC is still in progress,
such as might happen if `dev.timeout=1`, then it's possible
the `dev.close()` will encounter a
`ncclient.operations.errors.TimeoutExpiredError` exception.
Hanlde this exception and convert it to a `RpcTimeoutError`.

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Build finished. 730 tests run, 0 skipped, 0 failed.

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
ok to test

**Comment by jnpr-community-netdev** [comment]
Build triggered. sha1 is merged.

**Comment by jnpr-community-netdev** [comment]
Build started sha1 is merged.

**Comment by jnpr-community-netdev** [comment]
Build finished.

**Comment by vnitinv** [comment]
ok to test

**Comment by kokel** [comment]
What's the progress about this? We need this fix ...

**Comment by vnitinv** [comment]
@kokel @stacywsmith wondering in case of RpcTimeoutError should we be setting dev.connected to False?

**Comment by stacywsmith** [comment]
> @kokel @stacywsmith wondering in case of RpcTimeoutError should we be setting dev.connected to False?

No. You can't set `dev.connected` to False just because you received an `RpcTimeoutError`. The NETCONF session may still be open. It may simply be that the RPC is taking longer to execute than the allotted timeout. That doesn't necessarily mean it won't finish executing, or that the session is closed. I have seen cases where the timeout on an RPC request is intentionally set very low to ensure a "fast failure".

You could potentially catch the timeout exception inside the `close()` method and disconnect the underlying SSH session even though the `<close-session/>` RPC wasn't successfully sent/acknowledged.

**Review by rahkumar651991 — APPROVED** [review]

**Pull request merged**
