### PR TITLE
Feature: NSSU and ISSU Upgrade Selection

### PR DESCRIPTION
**Pull request by invaderlucky**
Added an upgrade type functionality that allows the user to run NSSU or ISSU upgrade. The install() method takes an additional parameter called "upType". This parameter can be an S, N, or I, for standard, NSSU, or ISSU. New methods are:

pgkaddNSSU()
      This uses the request_package_nonstop_upgrade.

pgkaddISSU()
      This uses the request_package_in_service_upgrade rpc call.

---
This change is [Reviewable](https://reviewable.io/reviews/juniper/py-junos-eznc/574)

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Autobot:  Would an admin like to run functional tests?

**Comment by vnitinv** [comment]
@invaderlucky Looks like the code changes was done on pretty old code and hence the code merge will break other functionalities. 
Also unit-tests need to be added for the new codes. I can help you with this.

**Comment by vnitinv** [comment]
@invaderlucky Dana I see you are calling function pkgupgrade but the given function is not defined anywhere in the class.

**Comment by vnitinv** [comment]
Taken care in #606

**Pull request closed without merging**
