### PR TITLE
Added a 'Search' function to PyEZ Tables and Views

### PR DESCRIPTION
**Pull request by goatshen**
I wanted Junos PyEZ Tables and Views to Regex a field. 
For Example, if the returned xml had the following element:

```
...
<interface-set-name>ae100-8080</interface-set-name>
...
```

With the new 'Search' function added to Factory_loader, it is now possible to extract the 'ae100' part. 
The PyEZ view will look like:

```
myView:
 fields:
  lag:  { interface-set-name : Search=(ae.+)- }
```

### CODE REVIEW

**Comment by goatshen** [comment]
Hi. Any feedback? @vnitinv

**Comment by vnitinv** [comment]
@goatshen Did you test with negative scenarios
re.search(pattern,text, re.M|re.I).groups(1)[0]
when search will fail (return None), groups(1) might be throwing NoneType Error.

**Comment by goatshen** [comment]
Thanks for the feedback. I'll look into it :)

**Comment by goatshen** [comment]
Thanks for the feedback. I'll look into it :)

**Comment by goatshen** [comment]
Hello. I handled the NoneType. What next?

**Comment by goatshen** [comment]
Hello @vnitinv 
I handled the nonetype. What next?

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by goatshen** [comment]
Hello. Could someone please verify the patch? Much Appreciated!

**Comment by goatshen** [comment]
Thank you so much!

**Pull request merged**
