### PR TITLE
support et-x/y/z interfaces #404

### PR DESCRIPTION
**Pull request by stianvi**
Quick fix for supporting et-* interfaces. Thanks @stacywsmith

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Autobot:  Would an admin like to run functional tests?

**Comment by vnitinv** [comment]
@stianvi Can you please share some example for the change to be working with and without a interface with et

**Comment by stianvi** [comment]
I can't get it working with get, et and xe interfaces, just vme - probably due to the dash:

playbook example:
```
    - name: Get IF info 40G
      junos_rpc:
        host: "{{ inventory_hostname }}"
        user: "{{ USERNAME }}"
        passwd: "{{ PASSWORD }}"
        rpc: "get-interface-information"
        kwargs: "interface_name=et-0/1/0"
        format: text
        dest: get_interface_information-et.conf
```

Request sent to switch:
```
Aug  5 13:42:51 [NETCONF] - [66651] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:a516f5af-73ec-49a1-b579-a0e775e6b6ee"><get-interface-information format="text"><interface-name>et</interface-name></get-interface-information></nc:rpc>]]>]]>

```

**Comment by stacywsmith** [comment]
@stianvi Your issue with junos_rpc is completely unrelated to this pull request. It really should be addressed as an issue against the Ansible junos modules.

The issue is with the parsing of the kwargs argument. As you can see from your NETCONF debugging, the interface name is incorrectly parsed/passed.
`<interface-name>et</interface-name>`

I believe the issue is with the regex here:
https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_rpc#L193

**Comment by stianvi** [comment]
Thanks @stacywsmith , fixed the regex in Juniper/ansible-junos-stdlib#153

I'll do the changes locally and can then continue the test requested by @vnitinv

**Comment by stianvi** [comment]
Think this always worked, unless junos_rpc don't use these files, because it works after I fixed regex in Juniper/ansible-junos-stdlib#153

I did a rollback and included the regex fix - it now shows all ge/xe/et files as expected.
```
$  grep fgx /usr/lib/python2.7/site-packages/jnpr/junos/op/*
/usr/lib/python2.7/site-packages/jnpr/junos/op/ethport.yml:    interface_name: '[afgx]e*'
/usr/lib/python2.7/site-packages/jnpr/junos/op/intopticdiag.yml:    interface_name: '[fgx]e*'
/usr/lib/python2.7/site-packages/jnpr/junos/op/phyport.yml:    interface_name: '[fgx]e*'
/usr/lib/python2.7/site-packages/jnpr/junos/op/phyport.yml:    interface_name: '[fgx]e*'
/usr/lib/python2.7/site-packages/jnpr/junos/op/phyport.yml:    interface_name: '[fgx]e*'
```

correct replies received when using ansible/junos_rpc:
```
$ cat get_if_* | egrep "^Phy"
Physical interface: et-0/1/0, Enabled, Physical link is Up
Physical interface: ge-0/0/30, Enabled, Physical link is Up
Physical interface: vme, Enabled, Physical link is Up
Physical interface: xe-0/0/29, Enabled, Physical link is Up
```

**Pull request merged**
