### PR TITLE
provide option to pass Null as alternate key with pipe

### PR DESCRIPTION
**Pull request by vnitinv**
Need the logical OR support for the key. 

```yaml
UTMStatusTable:
    rpc: show-utmd-status
    item:  //utmd-status
    view: UTMStatusView
    key: re-name | Null

UTMStatusView:
    fields:
        running: { running: flag }
```

We should be also able to support both item and key as logical OR operator
```yaml
UTMStatusTable:
    rpc: show-utmd-status
    item: //multi-routing-engine-item/utmd-status | //utmd-status
    view: UTMStatusView
    key: 
      - re-name | Null

UTMStatusView:
    fields:
        running: { running: flag }
```
Note: When the item is using OR operator, key need to be passed as list (the way code handles it)

Standalone Output:

root@snpsrx4600h> show security utm status | display xml 
```xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/19.2R0/junos">
    <utmd-status xmlns="http://xml.juniper.net/junos/19.2R0/junos-utmd">
        <running/>
    </utmd-status>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

In case of standalone, above table should return
```python
{'running': True}
```
High-Availability Output:

root@riad-srx4200-4> show security utm status | display xml 
```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/20.1I0/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>node0</re-name>
            
            <utmd-status xmlns="http://xml.juniper.net/junos/20.1I0/junos-utmd"><running/>
        </utmd-status>
    </multi-routing-engine-item>
    
    <multi-routing-engine-item>
        
        <re-name>node1</re-name>
        
        <utmd-status xmlns="http://xml.juniper.net/junos/20.1I0/junos-utmd"><running/>
    </utmd-status>
</multi-routing-engine-item>

    </multi-routing-engine-results>
    <cli>
<banner>{primary:node0}</banner>
    </cli>
</rpc-reply>
```

In case of cluster, above table/view should return
```python
{'node0': {'running': True}, 'node1': {'running': True}}
```

### CODE REVIEW

**Comment by rsmekala** [comment]
retest this please

**Comment by vnitinv** [comment]
ok to test

**Comment by vnitinv** [comment]
ok to test

**Comment by vnitinv** [comment]
retest this please

**Pull request merged**
