### PR TITLE
Drop support for EOL Python 2.6

### PR DESCRIPTION
**Pull request by hugovk**
Closes https://github.com/Juniper/py-junos-eznc/pull/806.

Python 2.6 is EOL and no longer receiving security updates. Due to this, dependencies have already dropped it and breaking the build.

Here's the pip installs for junos-eznc from PyPI for last month, showing it's also little used.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   71.8% |          6,535 |
| 3.5            |   10.5% |            958 |
| 3.6            |    9.1% |            825 |
| 3.4            |    8.4% |            763 |
| 2.6            |    0.2% |             21 |
| 3.3            |    0.1% |              5 |
| 3.7            |    0.0% |              1 |

Source: `pypinfo --start-date -46 --end-date -16 --percent --pip --markdown junos-eznc pyversion`

### CODE REVIEW

**Comment by jnpr-community-netdev** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
Can one of the admins verify this patch?

**Comment by vnitinv** [comment]
Thanks @hugovk 
Will do basic testing and then merge this.

**Comment by vnitinv** [comment]
ok to test

**Comment by vnitinv** [comment]
ok to test

**Comment by vnitinv** [comment]
ok to test

**Pull request merged**
